---
title: "boxplots_cutes"
author: "Nuria Sánchez de la Blanca Carrero"
date: "9/17/2021"
output: html_document
---

https://www.r-bloggers.com/2017/06/add-p-values-and-significance-levels-to-ggplots/
https://rkabacoff.github.io/datavis/Customizing.html


# LIBRARIES
```{r}
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(openxlsx)
```

# DATA
```{r}
probi <- read.xlsx("~/Desktop/Diabetes probi/PROBI_REVISADO/PROBI_rev_IMP.xlsx")
```


```{r}
compare_means(KpaFibrosis ~ Smoking, data = probi)
```



```{r}
#my_comparisons <- list( c("0", "1"), c("1", "2"), c("0", "2") )
#my_comparisons <- list( c("0", "1"),c("0", "2"), c("0", "3"),  c("1", "2"), c("1", "3"), c("2", "3") )
my_comparisons <- list( c("0", "1") )
```

```{r}
ggboxplot(data_prov, x = "GradoFibrosis", y =  "Shannon_Value",
          color = "GradoFibrosis", palette = "jco")+
  #stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 5)     # Add global p-value
```

```{r}
ggboxplot(probi, x = "Smoking", y = "CAPesteatosis", color = "Smoking", palette = "jco")+
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 600)     # Add global p-value
```